-- AlterTable
ALTER TABLE `task` ADD COLUMN `closedAt` DATETIME(3) NULL,
    MODIFY `status` ENUM('OPEN', 'COMPLETED', 'SKIPPED', 'MISSED') NOT NULL DEFAULT 'OPEN';

-- AlterTable
ALTER TABLE `subtask` MODIFY `status` ENUM('OPEN', 'COMPLETED', 'SKIPPED', 'MISSED') NOT NULL DEFAULT 'OPEN';
