export const PROJECT_COLOR_OPTIONS = Object.freeze([
  { id: "coral", label: "Coral", color: "#C95B49" },
  { id: "tangerine", label: "Tangerine", color: "#DF7942" },
  { id: "amber", label: "Amber", color: "#B98728" },
  { id: "rose", label: "Rose", color: "#C24F79" },
  { id: "plum", label: "Plum", color: "#925D9C" },
  { id: "indigo", label: "Indigo", color: "#6262A8" },
  { id: "cobalt", label: "Cobalt", color: "#426FA8" },
  { id: "tide", label: "Tide", color: "#398B91" },
  { id: "slate", label: "Slate", color: "#687583" },
  { id: "brick", label: "Brick", color: "#B66358" },
  { id: "copper", label: "Copper", color: "#AE7046" },
  { id: "apricot", label: "Apricot", color: "#CA8A65" },
  { id: "berry", label: "Berry", color: "#A45474" },
  { id: "orchid", label: "Orchid", color: "#A073AD" },
  { id: "periwinkle", label: "Periwinkle", color: "#7D7FBE" },
  { id: "denim", label: "Denim", color: "#547EA9" },
  { id: "lagoon", label: "Lagoon", color: "#558E9A" },
  { id: "graphite", label: "Graphite", color: "#837889" },
]);