-- MyManager Phase 1 SQL (MySQL 8+)
-- This mirrors the Prisma schema in prisma/schema.prisma.

CREATE TABLE project_types (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL UNIQUE,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
  deleted_at DATETIME NULL
);

CREATE TABLE priorities (
  id INT AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(10) NOT NULL UNIQUE,
  title VARCHAR(100) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
  deleted_at DATETIME NULL
);

CREATE TABLE project_colors (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  hex_code VARCHAR(7) NOT NULL UNIQUE,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
  deleted_at DATETIME NULL
);

CREATE TABLE projects (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  description TEXT NULL,
  type_id INT NOT NULL,
  color_id INT NOT NULL,
  priority_id INT NOT NULL,
  status ENUM('ACTIVE','HOLD','COMPLETED','ARCHIVED') NOT NULL DEFAULT 'ACTIVE',
  dp_image VARCHAR(255) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
  deleted_at DATETIME NULL,
  CONSTRAINT fk_projects_type FOREIGN KEY (type_id) REFERENCES project_types(id),
  CONSTRAINT fk_projects_color FOREIGN KEY (color_id) REFERENCES project_colors(id),
  CONSTRAINT fk_projects_priority FOREIGN KEY (priority_id) REFERENCES priorities(id)
);

CREATE TABLE tasks (
  id INT AUTO_INCREMENT PRIMARY KEY,
  project_id INT NOT NULL,
  name VARCHAR(150) NOT NULL,
  description TEXT NULL,
  priority_id INT NOT NULL,
  frequency ENUM('ONCE','DAILY','WEEKLY','MONTHLY','YEARLY') NOT NULL DEFAULT 'ONCE',
  alert_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  alert_before_minutes INT NULL,
  start_date_time DATETIME NULL,
  end_date_time DATETIME NULL,
  duration_minutes INT NULL,
  status ENUM('ACTIVE','IN_PROGRESS','COMPLETED','HOLD','IN_REVIEW','PENDING') NOT NULL DEFAULT 'PENDING',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
  deleted_at DATETIME NULL,
  CONSTRAINT fk_tasks_project FOREIGN KEY (project_id) REFERENCES projects(id),
  CONSTRAINT fk_tasks_priority FOREIGN KEY (priority_id) REFERENCES priorities(id)
);

CREATE TABLE subtasks (
  id INT AUTO_INCREMENT PRIMARY KEY,
  task_id INT NOT NULL,
  name VARCHAR(150) NOT NULL,
  description TEXT NULL,
  status ENUM('ACTIVE','IN_PROGRESS','COMPLETED','HOLD','IN_REVIEW','PENDING') NOT NULL DEFAULT 'PENDING',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
  deleted_at DATETIME NULL,
  CONSTRAINT fk_subtasks_task FOREIGN KEY (task_id) REFERENCES tasks(id)
);
